/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns 200 when the API process is alive. Does not check DB connectivity.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global statistics
         * @description Aggregate counts across all rounds and assets since contract deployment.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current active rounds for an asset
         * @description Returns up to 5 rounds for `asset` that are not yet Settled, ordered by
         *     settle_ts ascending. Typically 1–2 rows: one Open (accepting bets) and
         *     one Locked (awaiting oracle settlement).
         */
        get: operations["getCurrentRounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settled round history for an asset
         * @description Returns up to `limit` rounds for `asset`, ordered by settle_ts descending
         *     (most recent first). Includes all statuses. Max limit is 200.
         */
        get: operations["getRoundHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Single round by ID
         * @description Returns a single round record. Useful for polling a specific round's settle status.
         */
        get: operations["getRoundById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{address}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All positions for a Stellar address
         * @description Returns the 100 most recent bets placed by `address`, joined with the
         *     round's current state. Includes won, lost, pending, and void positions.
         *     Check `status` and `outcome` to determine if a position is claimable.
         */
        get: operations["getUserPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{address}/claimable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claimable positions for a Stellar address
         * @description Returns settled positions that have a non-zero payout and have not yet
         *     been claimed on-chain. The `claimable` field is the computed payout in
         *     stroops using the parimutuel formula. Void rounds return the original
         *     staked `amount`.
         *
         *     Use this endpoint to build the claim queue UI and display the total
         *     outstanding XLM the user can collect.
         */
        get: operations["getUserClaimable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top users by net P&L
         * @description Returns the top 100 users ranked by net P&L (`total_won - total_staked`)
         *     over the requested time window. Sourced from a materialised view refreshed
         *     roughly every 10 minutes.
         *
         *     Note: leaderboard rows read from the `leaderboard` materialised view for
         *     the all-time window; live SQL for time-windowed queries.
         */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket — live round state and indicative prices
         * @description Upgrade this connection to WebSocket. The server pushes messages without
         *     the client sending anything. Three message types are emitted:
         *
         *     **connected** — sent immediately on connection.
         *
         *     **round** — emitted every 5 seconds for every non-Settled round. Use
         *     this to drive countdown timers and live pool displays. Do not use the
         *     server clock from this message as the canonical time source; use the
         *     `settle_ts` and `lock_ts` fields.
         *
         *     **price** — emitted as Binance miniTicker ticks arrive (approximately
         *     every second). This is the *indicative* display price sourced from a
         *     CEX. It is **not** the settlement price. Settlement reads
         *     `oracle.price(asset, settle_ts)` from Reflector — a separate source
         *     that will differ slightly. Never confuse the two in UI copy.
         */
        get: operations["websocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Prediction market asset. XLM prices are from the Reflector USD-base oracle.
         * @enum {string}
         */
        Asset: "BTC" | "ETH" | "SOL" | "XLM";
        /**
         * @description Open — bets accepted until lock_ts.
         *     Locked — no new bets; awaiting the oracle tick at settle_ts.
         *     Settled — outcome determined; winners may claim.
         * @enum {string}
         */
        RoundStatus: "Open" | "Locked" | "Settled";
        /**
         * @description Up — settle_price > strike.
         *     Down — settle_price < strike.
         *     Void — exact tie, empty pool on either side, or oracle gap.
         *       Void rounds refund the gross staked amount with no fee deducted.
         *     Null when the round is not yet Settled.
         * @enum {string|null}
         */
        Outcome: "Up" | "Down" | "Void" | null;
        /**
         * @description Which direction the user bet on.
         * @enum {string}
         */
        Side: "Up" | "Down";
        Round: {
            /**
             * @description On-chain u64 ID, returned as a string to preserve precision.
             * @example 42
             */
            round_id: string;
            asset: components["schemas"]["Asset"];
            /**
             * @description Oracle price at round open (P_N). Raw i128 with 14 decimal places.
             *     Actual USD price = strike / 10^14. Used as the reference to compare
             *     against settle_price. Bettors are predicting whether the next oracle
             *     tick will be above or below this value.
             * @example 6303831631126319160
             */
            strike: string;
            /**
             * Format: int64
             * @description Unix timestamp (seconds) of the oracle tick that produced the strike. Derived from oracle.lastprice().timestamp — NOT from the ledger clock.
             * @example 1785577800
             */
            strike_ts: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds) after which bets are rejected. Equal to strike_ts + lock_offset (default 180s).
             * @example 1785577980
             */
            lock_ts: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds) at which oracle.price(asset, settle_ts) is read for settlement. Equal to strike_ts + 300.
             * @example 1785578100
             */
            settle_ts: number;
            /**
             * @description Total XLM staked on Up in stroops (1 XLM = 10,000,000 stroops). Updated on every Bet event.
             * @example 8000000000
             */
            pool_up: string;
            /**
             * @description Total XLM staked on Down in stroops.
             * @example 2000000000
             */
            pool_down: string;
            status: components["schemas"]["RoundStatus"];
            outcome?: components["schemas"]["Outcome"];
            /**
             * @description Oracle price at settle_ts (P_(N+1)). Null until Settled. Same 14-decimal encoding as strike.
             * @example 6400000000000000000
             */
            settle_price?: string | null;
            /**
             * Format: date-time
             * @description When the indexer first recorded this round.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the indexer recorded the Settled event. Null until settled.
             */
            settled_at?: string | null;
        };
        /** @description A bet joined with its round's current state. */
        UserPosition: {
            /** @description Internal database ID of the bet row. */
            id: number;
            /** @description Stellar transaction hash of the bet transaction. */
            tx_hash: string;
            /** @description Index of the Bet event within the transaction. */
            event_index: number;
            /**
             * @description On-chain round ID this bet is for.
             * @example 42
             */
            round_id: string;
            /** @description Stellar G-address of the bettor. */
            user_addr: string;
            side: components["schemas"]["Side"];
            /**
             * @description Amount staked in stroops.
             * @example 1000000000
             */
            amount: string;
            /** Format: date-time */
            placed_at: string;
            asset: components["schemas"]["Asset"];
            status: components["schemas"]["RoundStatus"];
            outcome?: components["schemas"]["Outcome"];
            /** Format: int64 */
            settle_ts: number;
            pool_up: string;
            pool_down: string;
            strike: string;
            settle_price?: string | null;
        };
        /** @description A settled position with a non-zero unclaimed payout. */
        ClaimablePosition: {
            /** @example 42 */
            round_id: string;
            side: components["schemas"]["Side"];
            /**
             * @description Original amount staked in stroops.
             * @example 1000000000
             */
            amount: string;
            outcome: components["schemas"]["Outcome"];
            /** @example 8000000000 */
            pool_up: string;
            /** @example 2000000000 */
            pool_down: string;
            settle_price?: string | null;
            strike: string;
            asset: components["schemas"]["Asset"];
            /** Format: int64 */
            settle_ts: number;
            /**
             * @description Computed payout in stroops using the parimutuel formula:
             *       distributed = (pool_up + pool_down) * (10000 - fee_bps) / 10000
             *       payout = amount * distributed / winning_pool
             *     For Void rounds: claimable = amount (gross refund, no fee).
             */
            claimable: string;
        };
        LeaderboardEntry: {
            /** @description Stellar G-address. */
            user_addr: string;
            /**
             * @description Distinct rounds bet on within the time window.
             * @example 24
             */
            rounds_entered: string;
            /**
             * @description Total stroops received from winning claims.
             * @example 15400000000
             */
            total_won: string;
            /**
             * @description Total stroops placed as bets.
             * @example 12000000000
             */
            total_staked: string;
            /**
             * @description total_won − total_staked in stroops. Can be negative.
             * @example 3400000000
             */
            net_pnl: string;
        };
        StatsResponse: {
            /**
             * @description All rounds ever indexed.
             * @example 288
             */
            total_rounds: string;
            /**
             * @description Rounds with status = Settled.
             * @example 276
             */
            settled_rounds: string;
            /**
             * @description Sum of pool_up + pool_down across all rounds, in stroops.
             * @example 2880000000000
             */
            total_volume: string;
            /**
             * @description Count of distinct assets that have at least one round.
             * @example 4
             */
            active_assets: string;
        };
        HealthResponse: {
            /** @example true */
            ok: boolean;
            /**
             * @description Server Unix timestamp in milliseconds.
             * @example 1785577900000
             */
            ts: number;
        };
        ErrorResponse: {
            /** @example asset required */
            error: string;
        };
        WsConnected: {
            /**
             * @description Sent once immediately after the WebSocket handshake.
             * @enum {string}
             */
            type: "connected";
        };
        WsRound: {
            /** @enum {string} */
            type: "round";
            /** @description Current state of a non-Settled round. Emitted every 5 seconds per round. */
            data: components["schemas"]["Round"];
        };
        WsPrice: {
            /** @enum {string} */
            type: "price";
            asset: components["schemas"]["Asset"];
            /**
             * @description Indicative USD price string from Binance miniTicker (field `c` = close).
             *     This is the DISPLAY price for the UI chart.
             *     It is NOT the settlement price — settlement uses oracle.price(asset, settle_ts)
             *     from Reflector, which will differ. Do not use this for any payout calculation.
             * @example 63412.50
             */
            price: string;
            /**
             * @description Server-side Date.now() in milliseconds when the tick was received.
             * @example 1785577912345
             */
            ts: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    getCurrentRounds: {
        parameters: {
            query: {
                /** @description Asset symbol. One of BTC, ETH, SOL, XLM. */
                asset: components["schemas"]["Asset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active rounds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"][];
                };
            };
            /** @description Missing or invalid asset query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRoundHistory: {
        parameters: {
            query: {
                /** @description Asset symbol. One of BTC, ETH, SOL, XLM. */
                asset: components["schemas"]["Asset"];
                /** @description Number of rounds to return. Capped at 200. Defaults to 50. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical rounds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"][];
                };
            };
            /** @description Missing or invalid asset query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRoundById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The on-chain round_id (u64, returned as a string). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Round found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            /** @description No round with this ID exists in the index */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserPositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stellar G-address of the user. */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of positions (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPosition"][];
                };
            };
        };
    };
    getUserClaimable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stellar G-address of the user. */
                address: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claimable positions (may be empty if nothing is owed) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimablePosition"][];
                };
            };
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                /** @description Time window. One of 24h, 7d, 30d. Defaults to 7d. */
                window?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
        };
    };
    websocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols — WebSocket upgrade accepted */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
